version: 0.0
os: linux
files:
  - source: /businessworldtemplate
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: root
